### PR TITLE
ES6 syntax + SGListView + Custom background

### PR DESCRIPTION
**Pull request by stoffern**
because that is a part of the future..

### CODE REVIEW

**Comment by stoffern** [comment]
cc @jeanpan 

more to come..

**Comment by jeanpan** [comment]
@stoffern. Thanks for the ES6 syntax change, but regarding multipick/singlepick, you can set props of maximum to have multipick or singlepick.

**Comment by stoffern** [comment]
@jeanpan ah, ok.. reverted the last commits regarding multipick. should be ok now.

**Comment by stoffern** [comment]
There is a problem with the height of the View. 
This overflows the view as flexWrap property is set.
Working on a fix, dont merge yet

**Comment by stoffern** [comment]
Tested ok on Android, should also be working on iOS.

cc @jeanpan

**Comment by superandrew213** [comment]
@stoffern you're not using SGListView

**Comment by stoffern** [comment]
@superandrew213 ups, forgot to change back to SGListView, it is there now.

**Comment by jeanpan** [comment]
@stoffern thanks ! Will merge it after check !

**Pull request merged**
