### PR TITLE
Updated README.md for the latest commit.

### PR DESCRIPTION
**Pull request by BROUDING**
Updated README.md for 'Advanced listView performance' commit.

### CODE REVIEW

**Comment by jeanpan** [comment]
@BROUDING, thanks for the PR but I just merged another PR https://github.com/jeanpan/react-native-camera-roll-picker/pull/23 which also updated the README.md. Could you help to pull the latest code and solve the conflict ? Thanks!

**Comment by BROUDING** [comment]
Sure sure ~

**Comment by BROUDING** [comment]
Done !

**Comment by jeanpan** [comment]
Great ! Thanks @BROUDING :)

**Pull request merged**
