### PR TITLE
return size of selected images, fix jeanpan/react-native-camera-roll-…

### PR DESCRIPTION
**Pull request by sibelius**
…picker#8

### CODE REVIEW

**Comment by stoffern** [comment]
please note that this is a **breaking change**

**Comment by sibelius** [comment]
it is! please bump a major version after merge this PR and this one https://github.com/jeanpan/react-native-camera-roll-picker/pull/7

**Comment by jeanpan** [comment]
@sibelius the PR #7 has been merged. Could you help to fix the conflict.

**Comment by stoffern** [comment]
https://github.com/jeanpan/react-native-camera-roll-picker/blob/master/index.js#L91
```js
onPress={event => this._selectImage(item.node.image.uri)}>
```
to
```js
onPress={event => this._selectImage(item.node.image)}>
```

https://github.com/jeanpan/react-native-camera-roll-picker/blob/master/index.js#L96
```js
{ (this.state.selected.indexOf(item.node.image.uri) >= 0)? selectedMarker : null }
```
to
```js
{ (this.state.selected.indexOf(item.node.image) >= 0)? selectedMarker : null }
```

cc @jeanpan @sibelius

**Comment by sibelius** [comment]
closing in favor of this one https://github.com/jeanpan/react-native-camera-roll-picker/pull/10

**Pull request closed without merging**
